#!/bin/bash
yum update -y
yum install -y git
yum install -y docker
service docker start
usermod -a -G docker ec2-user
chkconfig docker on
git clone https://github.com/cs220s23/BestGroupProject.git /BestGroupProject
cd /BestGroupProject
docker build ./collector -t collector
docker build ./server -t server
docker network create covid
./up_aws
