name: Merge Pull Request

# only trigger on pull request closed events
on:
  pull_request_target:
    types: [closed]

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: notifying the console that merge has occured
      run: |
        echo PR #${{ github.event.number }} has been merged
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.AWS_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }} 
        script: /BestGroupProject/update_merge
        
  close_job:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merged
